"use client";
import { FileArrowUp, SealCheck } from "@phosphor-icons/react";
import { useState } from "react";
import { buildApiHeaders } from "../lib/clientAuth";
import { useSensitiveFetch } from "./MfaStepUpProvider";
import { PurchasePreviewTable, type PurchasePreviewRow } from "./PurchasePreviewTable";

type Preview = { summary: { lineCount: number; uniquePartNumbers: number; quantity: number; subtotalMinor: number; discountMinor: number; finalTotalMinor: number; riskCounts: { low: number; medium: number; high: number }; supplementedLines: number }; warnings: string[]; sourceSha256: string; lines: PurchasePreviewRow[] };
export function PurchaseImportPanel() {
  const sensitiveFetch = useSensitiveFetch();
  const [pi, setPi] = useState<File | null>(null); const [supplemental, setSupplemental] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [token, setToken] = useState(""); const [message, setMessage] = useState("Select the authoritative PI and optional packing JSON. Preview writes no business data.");
  async function send(mode: "preview" | "commit") { if (!pi) { setMessage("Select the authoritative PI first."); return; } const form = new FormData(); form.set("pi", pi); if (supplemental) form.set("supplemental", supplemental); if (mode === "commit") { form.set("previewToken", token); form.set("idempotencyKey", crypto.randomUUID()); } setMessage(mode === "preview" ? "Validating file hash and control totals..." : "Committing approved purchase data..."); const response = await sensitiveFetch(`/api/admin/imports/purchase-order/${mode}`, { method: "POST", headers: await buildApiHeaders("admin"), body: form }); const body = await response.json(); if (!response.ok || !body.ok) { setMessage(body.message || "Purchase import failed."); return; } if (mode === "preview") { setPreview(body.preview); setToken(body.previewToken); setMessage("Preview passed. Review the totals and risk split before commit."); } else { setMessage(`Import committed as ${body.importRunId}. All 706 units remain on order and unavailable.`); setToken(""); } }
  return <section className="panel import-panel" id="purchasing"><div className="panel-title"><div><p className="eyebrow">Controlled import</p><h2>Authoritative purchase order</h2></div><FileArrowUp size={28} weight="duotone" /></div><div className="form-grid"><label>Authoritative PI (.xlsx)<input type="file" accept=".xlsx" onChange={(e) => setPi(e.target.files?.[0] ?? null)} /></label><label>Packing supplement (.json)<input type="file" accept=".json" onChange={(e) => setSupplemental(e.target.files?.[0] ?? null)} /></label></div><div className="import-actions"><button className="button button-secondary" type="button" onClick={() => void send("preview")}>Preview &amp; validate</button><button className="button button-primary" type="button" disabled={!token} onClick={() => void send("commit")}><SealCheck size={18} />Commit approved preview</button><p role="status">{message}</p></div>{preview && <><div className="import-summary"><div><span>Lines</span><strong>{preview.summary.lineCount}</strong></div><div><span>Units on order</span><strong>{preview.summary.quantity}</strong></div><div><span>Cash PO cost</span><strong>RMB {(preview.summary.finalTotalMinor / 100).toLocaleString("en-AU", { minimumFractionDigits: 2 })}</strong></div><div><span>Risk split</span><strong>{preview.summary.riskCounts.high} H / {preview.summary.riskCounts.medium} M / {preview.summary.riskCounts.low} L</strong></div><div><span>Packing matched</span><strong>{preview.summary.supplementedLines} / 119</strong></div><div><span>Source hash</span><code>{preview.sourceSha256.slice(0, 16)}...</code></div></div><PurchasePreviewTable rows={preview.lines} /></>}</section>;
}
